server:
  tomcat:
    uri-encoding: UTF-8
spring:
  application:
    name: zxp-blog
  profiles:
    active: dev
  # 多个接口上的@FeignClient(“相同服务名”)会报错，overriding is disabled。
  # 设置 为true ,即 允许 同名
  main:
    allow-bean-definition-overriding: true
  #关闭 springBoot 对json格式的 空检查
  jackson:
    serialization:
      #      time-zone: GMT+8
      #      date-format: yyyy-MM-dd HH:mm:ss
      FAIL_ON_EMPTY_BEANS: false
#  sleuth:
#    enabled: false
mybatis-plus:
  mapper-locations: classpath:/mapper/*.xml
  #指定需要扫描的枚举包，用于自定义的枚举字段的转换
#  typeEnumsPackage: com.keda.bean.ke.facepay.enums
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
  global-config:
    db-config:
      id-type: auto
      field-strategy: not_empty
      table-underline: true
      db-type: mysql
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
#日志配置

